services:
  public:
    image: itzg/minecraft-bedrock-server:latest
    container_name: ${SERVER_NAME}
    user: ${MY_UID}:${MY_GID}
    restart: always
    env_file:
      - ${ENV_FILE:-.env.mbs}
    tty: true
    stdin_open: true
    ports:
      - ${PORT_SERVER}:${PORT_SERVER}/udp
    expose:
      - 2222
    environment:
      ENABLE_SSH: "TRUE"
      EULA: "TRUE"
      VERSION: "LATEST"
      UID: ${MY_UID}
      GID: ${MY_GID}
      TZ: ${MY_TZ}
      SERVER_NAME: ${SERVER_NAME}
      LEVEL_NAME: ${WORLD_NAME}
    volumes:
      - "${DIR_SERVER}:/data"
  backup:
    image: kaiede/minecraft-bedrock-backup
    container_name: ${SERVER_NAME}-backup
    restart: always
    env_file:
      - ${ENV_FILE:-.env.mbs}
    depends_on:
      # Make sure the minecraft service starts before the backup
      - "public"
    environment:
      # Without this, your log timestamps will be in the GMT timezone.
      TZ: ${MY_TZ}
    volumes:
      # Map the Bedrock backup sidecar config separately from backup data.
      - "${DIR_REPO}/config/mbs/backup:/config"
      # Map your backups folder into /data
      # - /minecraft/backups:/data
      - "${DIR_BACKUP_WORLDS}:/data"
      # Map your server's data folder wherever you like
      # - /minecraft/public:/public
      - "${DIR_SERVER}:/public"
